apiVersion: ray.io/v1
kind: RayService
metadata:
  name: rayservice-sample
spec:
  serveConfigV2: |
    applications:
      - name: vllm-app
        import_path: llm:build_app
        route_prefix: /
        runtime_env:
          working_dir: "https://github.com/taigetco/ray-worker/raw/main/llm.zip"
        deployments:
          - name: VLLMDeployment
            model: "/data/model/Mistral-7B-Instruct-v02-AWQ"
            tensor-parallel-size: 1
  rayClusterConfig:
    rayVersion: '2.9.0' # should match the Ray version in the image of the containers
    ######################headGroupSpecs#################################
    # Ray head pod template.
    headGroupSpec:
      # The `rayStartParams` are used to configure the `ray start` command.
      # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
      # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
      rayStartParams:
        dashboard-host: '0.0.0.0'
      #pod template
      template:
        spec:
          volumes:
            - name: model
              hostPath:
                path: "/data/model/Mistral-7B-Instruct-v02-AWQ"
                type: Directory
          nodeSelector:
            role: head
          containers:
            - name: ray-head
              image: docker.io/library/rayvllm:latest
              imagePullPolicy: Never
              resources:
                limits:
                  cpu: 8
                  memory: 20Gi
                requests:
                  cpu: 8
                  memory: 20Gi
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
              volumeMounts:
                - mountPath: /data/model/Mistral-7B-Instruct-v02-AWQ
                  name: model
    workerGroupSpecs:
      # the pod replicas in this group typed worker
      - replicas: 1
        minReplicas: 1
        maxReplicas: 5
        # logical group name, for this called small-group, also can be functional
        groupName: vllm-group
        # The `rayStartParams` are used to configure the `ray start` command.
        # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
        # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
        rayStartParams: {}
        #pod template
        template:
          spec:
            nodeSelector:
              role: worker
            volumes:
              - name: model
                hostPath:
                  path: "/data/model/Mistral-7B-Instruct-v02-AWQ"
                  type: Directory
            containers:
              - name: ray-worker # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
                image: docker.io/library/rayvllm:latest
                imagePullPolicy: Never
                env:
                  - name: HF_ENDPOINT
                    value: https://hf-mirror.com
                  - name: HUGGING_FACE_HUB_TOKEN
                    value: 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
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh","-c","ray stop"]
                resources:
                  limits:
                    cpu: "7"
                    memory: "18Gi"
                    nvidia.com/gpu: "1"
                  requests:
                    cpu: "4"
                    memory: "18Gi"
                    nvidia.com/gpu: "1"
                volumeMounts:
                  - mountPath: /data/model/Mistral-7B-Instruct-v02-AWQ
                    name: model