apiVersion: ray.io/v1
kind: RayService
metadata:
  name: rayservice-vllm
spec:
  serveConfigV2: |
    applications:
      - name: vllm_app
        route_prefix: /vllm
        import_path: llm.build_llm_app
        runtime_env:
          working_dir: "https://github.com/taigetco/ray-worker/raw/main/llm.zip"
        args:
          model: '/data/model/Mistral-7B-Instruct-v02-AWQ'
          tensor-parallel-size: 2
  rayClusterConfig:
    rayVersion: '2.9.0'
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          volumes:
            - name: model
              hostPath:
                path: "/data/model/Mistral-7B-Instruct-v02-AWQ"
                type: Directory
          nodeSelector:
            role: head
          containers:
            - name: ray-head
              image: docker.io/library/rayvllm:latest
              imagePullPolicy: Never
              resources:
                limits:
                  cpu: 2
                  memory: 4Gi
                requests:
                  cpu: 2
                  memory: 4Gi
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
              volumeMounts:
                - mountPath: /data/model/Mistral-7B-Instruct-v02-AWQ
                  name: model
    workerGroupSpecs:
      - replicas: 1
        minReplicas: 1
        maxReplicas: 5
        groupName: vllm-group
        rayStartParams: {}
        template:
          spec:
            nodeSelector:
              role: worker
            volumes:
              - name: model
                hostPath:
                  path: "/data/model/Mistral-7B-Instruct-v02-AWQ"
                  type: Directory
            containers:
              - name: ray-worker # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
                image: docker.io/library/rayvllm:latest
                imagePullPolicy: Never
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh","-c","ray stop"]
                resources:
                  limits:
                    cpu: "2"
                    memory: "4Gi"
                    nvidia.com/gpu: "1"
                  requests:
                    cpu: "2"
                    memory: "4Gi"
                    nvidia.com/gpu: "1"
                volumeMounts:
                  - mountPath: /data/model/Mistral-7B-Instruct-v02-AWQ
                    name: model